

name: Daily YouTube Pipeline

on:
  schedule:
    - cron: '30 2 * * *'

  workflow_dispatch:

jobs:
  run-notebook:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install gspread oauth2client google-api-python-client isodate pandas

      - name: Run Colab Notebook
        uses: colab-on-github/action@v1
        with:
          notebook: 'YT_Pipeline.ipynb'

        env:
          GOOGLE_SERVICE_ACCOUNT_KEY_CONTENT: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY_CONTENT }}
